### PR TITLE
Add border-radius support

### PR DESCRIPTION
**Pull request by Alexandre-Chapelle**
###  Changes
 - Added a loop to generate border-radius classes based on predefined values.
 - Defined variables for border-radius types and name
 - Updated documentation to include 'borderRadius' prop

### Why
  - This allows developers to effortlessly apply border-radius. 
  - Needed this feature myself, implemented it locally and than thought to myself that I'm probably not the only one and it could benefit other users.

### Testing
 - Verified that all generated border-radius classes apply the correct styles.
 - Ensured that existing styles are not broken by these additions.

### CODE REVIEW

**Comment by WOLFRIEND** [comment]
@Alexandre-Chapelle 
Hi. Thank you for your interest and contribution to the library, it is crucial to me.
At the moment I am investigating to what extent it may be useful. During development, there were thoughts about this functionality, but I tried to stick to the idea that the library should not mutate the elements to which it is applied.
And also, will it not intersect with other use cases. It will take me some time, but I will try to solve it in the nearest time.

**Comment by WOLFRIEND** [comment]
@Alexandre-Chapelle 
@Alexandre-Chapelle
Hi, I've reviewed your contribution and merged it. I made small changes and fixed typos. Thanks again for your contribution!
I will consider expanding this feature in the future.
If you don't mind, feel free to add me on LinkedIn (it's specified in my GitHub account), I'd like to mention you in the post about your contribution.

**Comment by Alexandre-Chapelle** [comment]
@WOLFRIEND 
Hey! Thanks for reviewing the PR. I've added you on LinkedIn.

I'd love to contribute more to this library in the future, but I have a question.

I think it would be great if the library had skeleton customizable presets, such as:
- Presets for a loading bullet list or numbered list
- Presets for a loading user card
- Presets for a loading image
...

Here's an example what it could look like
image

But as far as I understood the library aims for simplicity and lightweightness. So my question is: would adding this functionality be appropriate for this library?

**Comment by WOLFRIEND** [comment]
@Alexandre-Chapelle 
Sorry, can't find you there, could you, please, send me a direct message: https://www.linkedin.com/in/aleksandrtkachenko/

Regarding the presets, yeah, I was thinking about their possibilities, but there are a few key points why I didn't implement them:
- As you mentioned, I wanted this library to be simple and lightweight as much as possible. Adding these presets probably involves adding JS, which opens up a whole new range of possibilities. I didn't want to reinvent yet another library, of which there are already quite a few.
- I spent a lot of time investigating this question and studying other libraries that have similar preset functionality. And it is impossible to predict all cases. Even if a project has some "User card" that seems to look more or less similar everywhere, but in the end, they still differ from project to project. And even using a preset, it still has to be configured, and customized, so that it matches the project. But the main idea was to make as few changes as possible. And, it's way easier to adjust your component (if needed of course) and set some predefined dimensions during the loading process.

**Pull request merged**
